services:
  db-trackmyfix:
    image: mysql:8.0
    container_name: db-trackmyfix
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: track_my_fix_db
    networks:
      - trackmyfix_net
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 5
      timeout: 10s
      interval: 30s
      start_period: 10s
  trackmyfix:
    build:
      dockerfile: ./backend/Dockerfile
      context: ./
    image: trackmyfix:latest
    container_name: trackmyfix
    mem_limit: 512m
    environment:
      DB_HOST: "jdbc:mysql://db-trackmyfix:3307/track_my_fix_db?createDatabaseIfNotExist=true&serverTimezone=UTC"
    networks:
      - trackmyfix_net
    ports:
      - 9091:9091
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      db-trackmyfix:
        condition: service_healthy
  front-trackmyfix:
    container_name: front
    build:
      dockerfile: ./frontend/Dockerfile
      context: ./
    image: front-trackmyfix
    volumes:
      - ./frontend/src:/usr/code/src
      - ./frontend/index.html:/usr/code/index.html
      - ./frontend/eslint.config.js:/usr/code/eslint.config.js
      - ./frontend/tailwind.config.js:/usr/code/tailwind.config.js
      - ./frontend/postcss.config.js:/usr/code/postcss.config.js
      - ./frontend/vite.config.js:/usr/code/vite.config.js
    ports:
      - 5173:5173
    environment:
      VITE_BACKEND_URL: http://localhost:9091
    networks:
      - trackmyfix_net
    depends_on:
      db-trackmyfix:
        condition: service_healthy
      trackmyfix:
        condition: service_started
  trackmyfix-test:
    profiles: ["test"]
    build:
      dockerfile: ./backend.dockerfile
      context: ./
      target: build
    container_name: trackmyfix-test
    environment:
      DB_HOST: "jdbc:mysql://db-trackmyfix:3306/track_my_fix_test_db?createDatabaseIfNotExist=true&serverTimezone=UTC"
    networks:
      - trackmyfix_net
    command: ["./mvnw", "test"]
    depends_on:
      db-trackmyfix:
        condition: service_healthy
networks:
  trackmyfix_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24
