services:
  db-trackmyfix:
    image: mysql:8.0
    container_name: db-trackmyfix
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: postgres
      MYSQL_PASSWORD: postgres
      MYSQL_USER: postgres
      MYSQL_DATABASE: track_my_fix_db
      MYSQL_HOST: db-trackmyfix

    ports:
      - 8081:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 5
      timeout: 10s
  trackmyfix:
    build:
      dockerfile: Dockerfile
      context: ./
    image: eclipse-temurin
    container_name: trackmyfix
    mem_limit: 512m
    environment:
      DB_HOST: "jdbc:mysql://db-trackmyfix:3306/track_my_fix_db?createDatabaseIfNotExist=true&serverTimezone=UTC"
      DB_USER: postgres
      DB_PASSWORD: postgres
      ACCESS_SECRET: bXlTZWNyZXRLZXlGb3JBY2Nlc3NUb2tlbnM=
      REFRESH_SECRET: cmVmcmVzaFNlY3JldEtleUZvclJlZnJlc2hUb2tlbnM=
      REFRESH_EXPIRATION: 900000
      ACCESS_EXPIRATION: 3600000
    ports:
      - 9091:9091
    depends_on:
      db-trackmyfix:
        condition: service_healthy
